version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - cd src && doxygen Doxyfile

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py

formats:
  - html
