version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  # MUST be inside the build section
  apt_packages:
    - doxygen
  jobs:
    pre_build:
      - cd src && doxygen Doxyfile

python:
  install:
    # Ensure this file exists at the root of /docs/
    - requirements: docs/requirements.txt

sphinx:
  # Since you confirmed it's in docs/source/
  configuration: docs/source/conf.py
